server:
  address: 0.0.0.0
  port: 8080

security:
  ignored:
    - "*.bundle*"

token-expiration: 864_000_000 # 10 days
token-gen-secret: fj&F0f+=jfn2n2nf

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: cyclegan
